#!/usr/bin/env sh

pwd
ls -la 
ADDON_NAME=$(ls $INPUT_APP_PATH)
# ADDON_FULL_PATH=$(pwd)/$INPUT_APP_PATH
ADDON_FULL_PATH=./$INPUT_APP_PATH

echo "$INPUT_USERNAME" "$INPUT_PASSWORD" "$ADDON_FULL_PATH" "$INPUT_INCLUDED_TAGS" "$INPUT_EXCLUDED_TAGS" "$INPUT_LOG_LEVEL"

python3 /main.py "$INPUT_USERNAME" "$INPUT_PASSWORD" "$ADDON_FULL_PATH" "$INPUT_INCLUDED_TAGS" "$INPUT_EXCLUDED_TAGS" "$INPUT_LOG_LEVEL"
